name: baize-editor
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: sulgweb/baize-editor-client:latest
    ports:
      - "6651:80"
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: sulgweb/baize-editor-server:latest
    environment:
      - NODE_ENV=production
    restart: unless-stopped
