name: baize-editor
services:
  client:
    build:
      context: .
      dockerfile: docker/client-dockerfile
    image: sulgweb/baize-editor-client:latest
    ports:
      - "6651:80"
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: docker/server-dockerfile
    image: sulgweb/baize-editor-server:latest
    environment:
      - NODE_ENV=production
    restart: unless-stopped
